FROM python:3.8-windowsservercore-1809

ENV PYTHONFAULTHANDLER=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONHASHSEED=random \
    PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=100


WORKDIR /code

RUN pip install poetry
RUN poetry config virtualenvs.create false
RUN pip install pyinstaller

COPY . .

RUN poetry install -n --no-ansi

CMD "powershell .\bundle\build_win.ps1"