from s2ctl import (  # noqa: F401
    cmd_affinity_group,
    cmd_ansible,
    cmd_autocomplete,
    cmd_context,
    cmd_domain,
    cmd_gateway,
    cmd_metainfo,
    cmd_network,
    cmd_project,
    cmd_server,
    cmd_sshkey,
    cmd_task,
    cmd_vmware,
    cmd_vmware_server,
)
